[project]
name = "gov-domains"
version = "1.0.0"
description = "Track various government domain"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipwhois>=1.3.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
